Style/FrozenStringLiteralComment:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Documentation:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false