language: ruby
rvm:
  - 2.5.0  

install: 
  - gem install bundler
  - bundle install

services: postgresql

addons: 
  postgresql: 9.6
 
before_script:
  - psql -U postgres -c 'CREATE DATABASE user_test;'   
  - psql -U postgres -c 'CREATE DATABASE post_test;'
  - rails db:create
  - rails db:migrate 

script:
  - bundle exec rake    
  - bundle exec rspec