language: ruby
rvm:
 - 2.5.0
os: osx
services:
  - postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake

before_script:
  - psql -c 'create database pgapp_test;' -U postgres

