language: ruby
rvm:
  - 2.5.0  

install: 
  - gem uninstall bundler
  - gem install bundler
  - bundle install

services: postgresql
 
before_script:
  - rails db:create
  - rails db:migrate 

script:
  - bundle exec rake    
  - bundle exec rspec