language: ruby
rvm:
  - 2.5.0  
os: osx

install: 
  - bundle install
  - rails db:create
  - rails db:migrate 
services:
  - postgresql

before_script: 
  - psql -U postgres -c 'CREATE DATABASE user_test;'   
  - psql -U postgres -c 'CREATE DATABASE post_test;'

script:
  - bundle exec rake    
  - bundle exec rspec