services:
    - postgresql
os: osx
addons:
    postgresql: '12.3'

before_script:
    - cp config/database.yml.travis config/database.yml

language: ruby

rvm:
    - 2.5.0

script:
    - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
    - bundle exec rspec

